# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1fed0065b9d95874dbe1ae069cd2ea13"
name = "josh-dev"
handle = "josh-dev"
application_url = "https://laboratory-syndrome-himself-commercial.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "preorderapp1.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nat-parent-eds-solution.trycloudflare.com/auth/callback",
  "https://nat-parent-eds-solution.trycloudflare.com/auth/shopify/callback",
  "https://nat-parent-eds-solution.trycloudflare.com/api/auth/callback",
  "https://laboratory-syndrome-himself-commercial.trycloudflare.com/auth/callback",
  "https://laboratory-syndrome-himself-commercial.trycloudflare.com/auth/shopify/callback",
  "https://laboratory-syndrome-himself-commercial.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://robertson-milan-surf-limitation.trycloudflare.com/webhooks/app/uninstalled"

[pos]
embedded = false
