# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fd34c71f2060efc15512f060b242916"
application_url = "https://electric-patrol-wifi-requests.trycloudflare.com"
embedded = true
name = "extensive-upside-app"
handle = "extensive-upside-app-15"

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-3e2e3242.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://electric-patrol-wifi-requests.trycloudflare.com/auth/callback",
  "https://electric-patrol-wifi-requests.trycloudflare.com/auth/shopify/callback",
  "https://electric-patrol-wifi-requests.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
