# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "038b89df51f2a6ec76517eb5f3b640f0"
name = "extensive-upside-app-v2"
handle = "extensive-upside-app-v2"
application_url = "https://biol-za-headers-rapids.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "preorderapp1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sea-lion-app-ojpqw.ondigitalocean.app/auth/callback",
  "https://sea-lion-app-ojpqw.ondigitalocean.app/auth/shopify/callback",
  "https://sea-lion-app-ojpqw.ondigitalocean.app/api/auth/callback",
  "https://biol-za-headers-rapids.trycloudflare.com/auth/callback",
  "https://biol-za-headers-rapids.trycloudflare.com/auth/shopify/callback",
  "https://biol-za-headers-rapids.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
