# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "038b89df51f2a6ec76517eb5f3b640f0"
application_url = "https://stated-attempts-adopt-pat.trycloudflare.com"
embedded = true
name = "extensive-upside-app-v2"
handle = "extensive-upside-app-v2"

[build]
include_config_on_deploy = true
dev_store_url = "preorderapp1.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://stated-attempts-adopt-pat.trycloudflare.com/auth/callback",
  "https://stated-attempts-adopt-pat.trycloudflare.com/auth/shopify/callback",
  "https://stated-attempts-adopt-pat.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
