# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1fed0065b9d95874dbe1ae069cd2ea13"
name = "josh-dev"
handle = "josh-dev"
application_url = "https://walter-eng-phrases-freight.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "preorderapp1.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://walter-eng-phrases-freight.trycloudflare.com/auth/callback",
  "https://walter-eng-phrases-freight.trycloudflare.com/auth/shopify/callback",
  "https://walter-eng-phrases-freight.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
